<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>SEA.Infisical.Configuration</PackageId>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Description>ASP.NET Core configuration provider that loads Infisical secrets into IConfiguration and the process environment.</Description>
    <PackageTags>infisical;configuration;aspnetcore;secrets</PackageTags>
    <AssemblyName>SEA.Infisical.Configuration</AssemblyName>
    <RootNamespace>SEA.Infisical.Configuration</RootNamespace>
    <LangVersion>14</LangVersion>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Title>InfisicalSecretsConfiguration</Title>
    <Authors>SEA.Infisical.Configuration</Authors>
    <Copyright>SEA</Copyright>
    <Version>1.0.2</Version>
    <PackageProjectUrl>https://github.com/Shulyakovskiy/SEA.Infisical.Configuration</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Shulyakovskiy/SEA.Infisical.Configuration</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
      <PackageReference Include="Infisical.Sdk" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <None Include="../../README.md" Link="README.md" Pack="true" PackagePath="/" />
  </ItemGroup>

</Project>
